### ISSUE TITLE
Sky Sports has bleed using GIMP 

### ISSUE THREAD

**Issue by AbuBaniaz** [Jasmeet181/mediaportal-uk-logos#15]
Sky sports has bleed when viewed using GIMP.

Fixed logo by @mcfly822 attached.
[Sky Sports.zip](https://github.com/Jasmeet181/mediaportal-uk-logos/files/1540907/Sky.Sports.zip)

**Comment by Jasmeet181** [comment]
Thanks, it's the same fix as those SVG Cleaner optimised logos, just copy it into a new document in Inkscape. It looks like all the logos on the Sky Sports website do this, on top of their wonky borders. 

P.S. Sky Deutschland and Italia haven't switched to the newer style lowercase Sky logos yet.
