### ISSUE TITLE
logo for Meet the Babes

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-uk-logos#23]
Lucky Star Renamed To Meet the Babes

https://www.facebook.com/meetthebabes/

[Meet the Babes.zip](https://github.com/Jasmeet181/mediaportal-uk-logos/files/3268408/Meet.the.Babes.zip)

**Comment by Jasmeet181** [comment]
Thanks Dalmore.

**Comment by dalmore72** [comment]
Thanks
