### ISSUE TITLE
The box

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-uk-logos#25]
New Logo ??

![screenshot](https://user-images.githubusercontent.com/16014375/65040797-8480ec80-d955-11e9-804e-0e801dc47a42.png)

![Theboxtvlogo](https://user-images.githubusercontent.com/16014375/65040808-8c409100-d955-11e9-9ed9-05a178167357.jpg)

**Comment by Jasmeet181** [comment]
Thanks Dalmore, I decided to skip this one when it changed. Apparently they're temporarily reusing their original 90's logo for a nostalgia month, they also haven't given it a unique name.
There's some discussion about it here:

- https://tvforum.uk/tvhome/box-nostalgia-spirit-44810/
- https://forums.digitalspy.com/discussion/comment/94418772#Comment_94418772

**Comment by dalmore72** [comment]
Thanks for explaining :)

**Comment by Jasmeet181** [comment]
The logo changed back today.
