### ISSUE TITLE
ITV channels 

### ISSUE THREAD

**Issue by 0845** [Jasmeet181/mediaportal-uk-logos#26]
Can you get updated icons for the below UK Channels please. 

ITV Anglia East HD 
ITV Central West HD
ITV Cymru Wales HD 
ITV Granada HD
ITV London HD 
ITV Meridian East HD 
ITV Tyne Tees HD
ITV Westcountry (East) HD 
ITV Westcountry (West) HD 
ITV Yorkshire West HD
ITV Meridian South Coast
ITV Meridian Thames Valley

**Comment by Jasmeet181** [comment]
A logo for ITV Cymru Wales HD is already available. It's possible to make the others but the channels are labelled ITV or ITV HD and MediaPortal requires the channel and filename to match. The micro regions don't have their own logos AFAIK.

**Comment by 0845** [comment]
Same goes to the below channel you have done others but this one missing Logo

BBC one Cambridgeshire

**Comment by Jasmeet181** [comment]
Cambridgeshire gets the west version of BBC One East http://www.digitalbitrate.com/dtv.php?liste=30&live=1&lang=en&phrase=BBC%20One%20East

The logo on-screen just says East https://www.youtube.com/watch?v=_3tYbJblAJE

**Comment by 0845** [comment]
check 

http://www.digitalbitrate.com/dtv.php?liste=2&live=403&lang=en

and view BBC One Cambridge

**Comment by Jasmeet181** [comment]
iPlayer is handled by OnlineVideos, here's the support thread https://forum.team-mediaportal.com/threads/bbc-iplayer-uk.130713/

**Comment by 0845** [comment]
https://www.bbc.co.uk/schedules/p00fzl6h
