### ISSUE TITLE
Uk channel requests

### ISSUE THREAD

**Issue by 0845** [Jasmeet181/mediaportal-uk-logos#27]
Possible to get the below logos for Uk 

High Street TV 2
High Street TV 3
High Street TV 4
High Street TV 5
PaversShoes
Mta-Muslim tv

Ireland channel
Virgin Three HD
Eir Sports 2 HD
Eir Sport 1
Eir Sport 2

**Comment by Dealz-416LS** [comment]
👍 for this request.

Virgin Three HD & Eir Sports 2 HD would be great!

**Comment by Jasmeet181** [comment]
High Street TV doesn't have individual numbered logos.
The other two are already present as Pavers and MTA1.
I had the other Eir Sport channels until they were removed from Sky, the files are still accessible through the commit history at https://github.com/Jasmeet181/mediaportal-uk-logos/commit/1dfaed521169f68c42f4203125bf3cbfb72d0cac and https://github.com/Jasmeet181/mediaportal-uk-logos/commit/6a1936683ca56e100d4bb5d95e7a76be014505d6
If someone can provide an [export](https://www.team-mediaportal.com/wiki/display/MediaPortal1/Import%20-%20Export) with the Irish channels, I'll add them back in along with Virgin Three HD.
