### ISSUE TITLE
[Question] Kodi PVR Logos 

### ISSUE THREAD

**Issue by sammy2142** [Jasmeet181/mediaportal-uk-logos#29]
Hi thanks for this awesome collection :)
I have created some 800x450 size logo's from your svg/png source files to use with my HDhomerun and Kodi installation.
Is it ok with you if I post these modified logos on the Kodi forums for other users to use (of course crediting you and anyone else who contributed)
Regards

**Comment by Jasmeet181** [comment]
Go for it, I'd appreciate a link back though, it might help attract some contributors.

**Comment by sammy2142** [comment]
Awesome thanks - I have put a link back
