### ISSUE TITLE
Uk 

### ISSUE THREAD

**Issue by K08242** [Jasmeet181/mediaportal-uk-logos#32]
Sky sports NFL logo is missing

**Comment by Lexzie** [comment]
Maybe this will help: https://github.com/picons/picons/pull/309

**Comment by dalmore72** [comment]
New logo

![Sky sports NFL HD](https://user-images.githubusercontent.com/16014375/93255413-2cfca300-f79a-11ea-8a7c-191a6a0504a9.png)
![Sky sports NFL](https://user-images.githubusercontent.com/16014375/93255414-2e2dd000-f79a-11ea-8534-d2bdb20435d6.png)
